import os
import pytest

from project.graph_tools import *


def test_create_and_save_two_cycles_graph():
    create_and_save_two_cycles_graph(2, 5, ["a1", "a2"], "test.dot")

    assert (
        open("test.dot", "r").read()
        == """digraph  {
1;
2;
0;
3;
4;
5;
6;
7;
1 -> 2  [key=0, label=a1];
2 -> 0  [key=0, label=a1];
0 -> 1  [key=0, label=a1];
0 -> 3  [key=0, label=a2];
3 -> 4  [key=0, label=a2];
4 -> 5  [key=0, label=a2];
5 -> 6  [key=0, label=a2];
6 -> 7  [key=0, label=a2];
7 -> 0  [key=0, label=a2];
}
"""
    )
    os.remove("test.dot")


def test_load_graph_with_bad_input():
    with pytest.raises(FileNotFoundError):
        load_graph("sebas")


def test_load_graph_with_good_input():
    g = load_graph("generations")
    assert g.number_of_nodes() == 129
    assert g.number_of_edges() == 273


def test_get_graph_info():
    nodes_num, edges_num, labels = get_graph_info("skos")

    assert nodes_num == 144
    assert edges_num == 252
    assert labels == [
        "subPropertyOf",
        "label",
        "comment",
        "definition",
        "isDefinedBy",
        "type",
        "type",
        "definition",
        "type",
        "domain",
        "range",
        "label",
        "scopeNote",
        "type",
        "isDefinedBy",
        "seeAlso",
        "type",
        "title",
        "contributor",
        "description",
        "creator",
        "contributor",
        "creator",
        "contributor",
        "label",
        "definition",
        "type",
        "isDefinedBy",
        "subPropertyOf",
        "definition",
        "inverseOf",
        "type",
        "isDefinedBy",
        "subPropertyOf",
        "type",
        "label",
        "comment",
        "isDefinedBy",
        "subPropertyOf",
        "type",
        "definition",
        "scopeNote",
        "type",
        "label",
        "inverseOf",
        "label",
        "isDefinedBy",
        "subPropertyOf",
        "inverseOf",
        "type",
        "definition",
        "subPropertyOf",
        "type",
        "definition",
        "type",
        "type",
        "subPropertyOf",
        "inverseOf",
        "label",
        "scopeNote",
        "isDefinedBy",
        "type",
        "inverseOf",
        "definition",
        "type",
        "isDefinedBy",
        "comment",
        "label",
        "subPropertyOf",
        "scopeNote",
        "type",
        "isDefinedBy",
        "comment",
        "example",
        "comment",
        "type",
        "definition",
        "subPropertyOf",
        "type",
        "label",
        "subPropertyOf",
        "comment",
        "isDefinedBy",
        "comment",
        "type",
        "label",
        "definition",
        "type",
        "comment",
        "type",
        "definition",
        "subPropertyOf",
        "label",
        "isDefinedBy",
        "type",
        "comment",
        "type",
        "type",
        "label",
        "type",
        "isDefinedBy",
        "type",
        "subPropertyOf",
        "definition",
        "type",
        "label",
        "type",
        "definition",
        "comment",
        "type",
        "isDefinedBy",
        "type",
        "subPropertyOf",
        "subPropertyOf",
        "isDefinedBy",
        "type",
        "label",
        "inverseOf",
        "type",
        "range",
        "definition",
        "domain",
        "definition",
        "type",
        "label",
        "scopeNote",
        "isDefinedBy",
        "type",
        "range",
        "isDefinedBy",
        "type",
        "definition",
        "domain",
        "range",
        "type",
        "inverseOf",
        "label",
        "scopeNote",
        "label",
        "type",
        "definition",
        "isDefinedBy",
        "example",
        "disjointWith",
        "definition",
        "type",
        "range",
        "domain",
        "type",
        "isDefinedBy",
        "label",
        "unionOf",
        "type",
        "disjointWith",
        "isDefinedBy",
        "disjointWith",
        "scopeNote",
        "definition",
        "label",
        "type",
        "first",
        "rest",
        "first",
        "rest",
        "definition",
        "subPropertyOf",
        "label",
        "type",
        "isDefinedBy",
        "type",
        "label",
        "isDefinedBy",
        "type",
        "definition",
        "scopeNote",
        "type",
        "type",
        "label",
        "subPropertyOf",
        "definition",
        "comment",
        "type",
        "isDefinedBy",
        "comment",
        "definition",
        "type",
        "isDefinedBy",
        "scopeNote",
        "type",
        "label",
        "type",
        "label",
        "definition",
        "type",
        "subPropertyOf",
        "isDefinedBy",
        "type",
        "label",
        "isDefinedBy",
        "definition",
        "subPropertyOf",
        "type",
        "isDefinedBy",
        "inverseOf",
        "scopeNote",
        "subPropertyOf",
        "type",
        "type",
        "type",
        "definition",
        "label",
        "definition",
        "isDefinedBy",
        "label",
        "type",
        "comment",
        "range",
        "type",
        "type",
        "domain",
        "subClassOf",
        "scopeNote",
        "label",
        "definition",
        "type",
        "isDefinedBy",
        "subPropertyOf",
        "type",
        "type",
        "label",
        "isDefinedBy",
        "definition",
        "label",
        "isDefinedBy",
        "type",
        "definition",
        "subPropertyOf",
        "type",
        "type",
        "label",
        "subPropertyOf",
        "isDefinedBy",
        "definition",
        "type",
        "isDefinedBy",
        "subPropertyOf",
        "type",
        "type",
        "type",
        "label",
        "definition",
        "subPropertyOf",
    ]
