REGEXES = [
    "(abd*) | (abc*)",
    "(ab)*",
    "a*a*",
    "bbb",
    "(a | b | c)*(d | e | f)*",
    "a | a",
    "(ab) | (ac)",
    "abc*",
    "abc",
    "(abd) | (abc)",
    "a* | (a | b)*",
    "(a|b|c|d|e)(a|b|c|d|e)*",
    "(a|b)*(c|d)*",
    "(a|b)*",
    "a* | a",
    "(a|b|c|d|e)f*",
    "aa",
    "ab*",
    "ab",
    "ab*c*",
    "(ab) | (abc)",
    "a|c",
    "(a|c)(b|d)",
    "b",
    "a",
    "a*a*b",
    "((a | b)*c)*((d | e)*f)*",
    "((abd) | (abc))*",
    "(a|c)*",
    "((a | b) * c)*(d | e)",
    "a*b*",
    "(a | c)*(a | b)*",
    "(a | b)*(c | d)*(e | f)*",
    "a*(a | b)*",
    "(abd)* | (abc)*",
    "ab*c",
    "(aa)*",
    "a*",
    "(a|b|c|d|e)*",
    "((a|b)*c)*",
    "abcd",
]
