name: Run tests with pytest

on:
  push:
    branches:
      - '!main'
  pull_request:
    branches:
      - '!main'

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
        os: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip list

      - name: Generate parser
        working-directory: project/
        run: |
          rm -rf parser/MyGQL*
          antlr4 -o parser MyGQL.g4  -Dlanguage=Python3 -visitor

      - name: Run tests with pytest
        run: python ./scripts/run_tests.py
