name: Code style & linting

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-codestyle-lint
  cancel-in-progress: true

jobs:
  style:
    name: Code style & linting
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Sync dependencies
        run: rye sync

      - name: Install pre-commit
        run: |
          rye run -- pre-commit install

      - name: Run pre-commit
        run: |
          rye run -- pre-commit run --all-files --color always --verbose --show-diff-on-failure

      - name: Run ruff format
        run: rye fmt --check

      - name: Run ruff linter
        run: rye lint -- --output-format=github
