name: Check code style

on:
  push:
    branches:
      # PRs can only use caches from their target branch. We therefore need to
      # make sure we run on 'main' too.
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-codestyle
  cancel-in-progress: true

jobs:
  style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: poetry
          python-version: 3.9

      - name: Install requirements
        run: |
          poetry install

      - name: Install pre-commit
        run: |
          poetry run -- pre-commit install

      - name: Run pre-commit
        run: |
          poetry run -- pre-commit run --all-files --color always --verbose --show-diff-on-failure
